const moviesData = [
  {
    id: "m1",
    title: "Inception",
    poster: "https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    genre: ["Sci-Fi", "Action", "Thriller"],
    rating: 8.8,
    year: 2010,
    runtime: 148,
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    mood: ["Thought-provoking", "Action-packed", "Suspenseful"],
    trailer: "YoHD9XEInc0",
    streaming: ["Netflix", "Apple TV"],
    director: "Christopher Nolan",
    cast: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page"
  },
  {
    id: "m2",
    title: "The Dark Knight",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    genre: ["Action", "Crime", "Drama"],
    rating: 9.0,
    year: 2008,
    runtime: 152,
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    mood: ["Action-packed", "Scary", "Thought-provoking"],
    trailer: "EXeTwQWrcwY",
    streaming: ["Prime Video", "Apple TV"],
    director: "Christopher Nolan",
    cast: "Christian Bale, Heath Ledger, Aaron Eckhart"
  },
  {
    id: "m3",
    title: "Interstellar",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    genre: ["Sci-Fi", "Drama", "Adventure"],
    rating: 8.7,
    year: 2014,
    runtime: 169,
    description: "When Earth becomes uninhabitable, a team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival.",
    mood: ["Emotional", "Thought-provoking", "Relaxing"],
    trailer: "zSWdZVtXT7E",
    streaming: ["Prime Video", "Netflix"],
    director: "Christopher Nolan",
    cast: "Matthew McConaughey, Anne Hathaway, Jessica Chastain"
  },
  {
    id: "m4",
    title: "Spirited Away",
    poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg",
    genre: ["Animation", "Adventure", "Fantasy"],
    rating: 8.6,
    year: 2001,
    runtime: 125,
    description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    mood: ["Emotional", "Relaxing", "Thought-provoking"],
    trailer: "ByXuk9QqQkk",
    streaming: ["Netflix", "HBO Max"],
    director: "Hayao Miyazaki",
    cast: "Rumi Hiiragi, Miyu Irino, Mari Natsuki"
  },
  {
    id: "m5",
    title: "Parasite",
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    genre: ["Drama", "Thriller", "Comedy"],
    rating: 8.5,
    year: 2019,
    runtime: 132,
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    mood: ["Thought-provoking", "Suspenseful", "Emotional"],
    trailer: "5xH0HfJHsaY",
    streaming: ["Hulu", "Apple TV"],
    director: "Bong Joon Ho",
    cast: "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong"
  },
  {
    id: "m6",
    title: "Whiplash",
    poster: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/6bbZ6XyvgfjhCzjEN07RgFGv9um.jpg",
    genre: ["Drama", "Music"],
    rating: 8.5,
    year: 2014,
    runtime: 106,
    description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    mood: ["Emotional", "Suspenseful", "Action-packed"],
    trailer: "7d_jQy340Lw",
    streaming: ["Netflix", "Prime Video"],
    director: "Damien Chazelle",
    cast: "Miles Teller, J.K. Simmons, Melissa Benoist"
  },
  {
    id: "m7",
    title: "Dune: Part Two",
    poster: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5200bm.jpg",
    genre: ["Sci-Fi", "Action", "Adventure"],
    rating: 8.9,
    year: 2024,
    runtime: 166,
    description: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    mood: ["Action-packed", "Thought-provoking", "Suspenseful"],
    trailer: "Way9Dexny3w",
    streaming: ["HBO Max", "Apple TV"],
    director: "Denis Villeneuve",
    cast: "Timothée Chalamet, Zendaya, Rebecca Ferguson"
  },
  {
    id: "m8",
    title: "Spider-Man: Into the Spider-Verse",
    poster: "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7d6o00Su47S144p4V1qGfa0uK48.jpg",
    genre: ["Animation", "Action", "Adventure"],
    rating: 8.4,
    year: 2018,
    runtime: 117,
    description: "Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
    mood: ["Action-packed", "Relaxing", "Emotional"],
    trailer: "g4Hbz2jLXvQ",
    streaming: ["Disney+", "Netflix"],
    director: "Bob Persichetti, Peter Ramsey",
    cast: "Shameik Moore, Jake Johnson, Hailee Steinfeld"
  },
  {
    id: "m9",
    title: "Get Out",
    poster: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/u6nupU5hr1qytbMDjS96TqAwv4p.jpg",
    genre: ["Horror", "Mystery", "Thriller"],
    rating: 7.8,
    year: 2017,
    runtime: 104,
    description: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception eventually reaches a boiling point.",
    mood: ["Scary", "Suspenseful", "Thought-provoking"],
    trailer: "DzfpyUB60YY",
    streaming: ["Peacock", "Apple TV"],
    director: "Jordan Peele",
    cast: "Daniel Kaluuya, Allison Williams, Bradley Whitford"
  },
  {
    id: "m10",
    title: "Blade Runner 2049",
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/sAtoMqDVhNDQBc3QJL3RF6hlxGq.jpg",
    genre: ["Sci-Fi", "Action", "Mystery"],
    rating: 8.0,
    year: 2017,
    runtime: 164,
    description: "A new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos.",
    mood: ["Thought-provoking", "Relaxing", "Suspenseful"],
    trailer: "gCcx85zbxz4",
    streaming: ["HBO Max", "Prime Video"],
    director: "Denis Villeneuve",
    cast: "Ryan Gosling, Harrison Ford, Ana de Armas"
  },
  {
    id: "m11",
    title: "The Shawshank Redemption",
    poster: "https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    genre: ["Drama"],
    rating: 9.3,
    year: 1994,
    runtime: 142,
    description: "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
    mood: ["Emotional", "Thought-provoking", "Relaxing"],
    trailer: "PLl99DfY644",
    streaming: ["HBO Max", "Apple TV"],
    director: "Frank Darabont",
    cast: "Tim Robbins, Morgan Freeman, Bob Gunton"
  },
  {
    id: "m12",
    title: "Pulp Fiction",
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    genre: ["Crime", "Drama"],
    rating: 8.9,
    year: 1994,
    runtime: 154,
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    mood: ["Action-packed", "Thought-provoking", "Suspenseful"],
    trailer: "s7EdQ4FqbhY",
    streaming: ["Paramount+", "Apple TV"],
    director: "Quentin Tarantino",
    cast: "John Travolta, Uma Thurman, Samuel L. Jackson"
  },
  {
    id: "m13",
    title: "Mad Max: Fury Road",
    poster: "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/nlCHUW2Y9XWbuEUQauCBgnY8ymF.jpg",
    genre: ["Action", "Sci-Fi", "Adventure"],
    rating: 8.1,
    year: 2015,
    runtime: 120,
    description: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
    mood: ["Action-packed", "Suspenseful", "Emotional"],
    trailer: "hEJnMQG56iU",
    streaming: ["HBO Max", "Apple TV"],
    director: "George Miller",
    cast: "Tom Hardy, Charlize Theron, Nicholas Hoult"
  },
  {
    id: "m14",
    title: "La La Land",
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkVJb0Rf0.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/qJeU7KM4nT2C1WpOrw8zgIR049v.jpg",
    genre: ["Comedy", "Drama", "Music"],
    rating: 8.0,
    year: 2016,
    runtime: 128,
    description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    mood: ["Emotional", "Relaxing", "Thought-provoking"],
    trailer: "0pdqf4P9MB8",
    streaming: ["Netflix", "Apple TV"],
    director: "Damien Chazelle",
    cast: "Ryan Gosling, Emma Stone, Rosemarie DeWitt"
  },
  {
    id: "m15",
    title: "The Matrix",
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/p732kPZlB58540cT4m6Mtzc1oM5.jpg",
    genre: ["Sci-Fi", "Action"],
    rating: 8.7,
    year: 1999,
    runtime: 136,
    description: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    mood: ["Action-packed", "Thought-provoking", "Suspenseful"],
    trailer: "vKQi3bBA1y8",
    streaming: ["HBO Max", "Apple TV"],
    director: "The Wachowskis",
    cast: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss"
  },
  {
    id: "m16",
    title: "Avatar: The Way of Water",
    poster: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    genre: ["Sci-Fi", "Action", "Adventure"],
    rating: 7.6,
    year: 2022,
    runtime: 192,
    description: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
    mood: ["Action-packed", "Emotional", "Relaxing"],
    trailer: "d9MyW72ELq0",
    streaming: ["Disney+", "HBO Max"],
    director: "James Cameron",
    cast: "Sam Worthington, Zoe Saldana, Sigourney Weaver"
  },
  {
    id: "m17",
    title: "Joker",
    poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    genre: ["Crime", "Drama", "Thriller"],
    rating: 8.4,
    year: 2019,
    runtime: 122,
    description: "A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain in a gritty, realistic Gotham City.",
    mood: ["Emotional", "Thought-provoking", "Scary"],
    trailer: "zAGVQLHvwOY",
    streaming: ["HBO Max", "Apple TV"],
    director: "Todd Phillips",
    cast: "Joaquin Phoenix, Robert De Niro, Zazie Beetz"
  },
  {
    id: "m18",
    title: "A Quiet Place",
    poster: "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/roYyPiQDzKmIKUEyO91569tqRI.jpg",
    genre: ["Horror", "Sci-Fi", "Thriller"],
    rating: 7.5,
    year: 2018,
    runtime: 90,
    description: "A family struggles for survival in a world where most humans have been killed by blind but noise-sensitive creatures. They are forced to communicate only in sign language to keep the creatures at bay.",
    mood: ["Scary", "Suspenseful", "Emotional"],
    trailer: "WR7cc5t7niU",
    streaming: ["Paramount+", "Hulu"],
    director: "John Krasinski",
    cast: "Emily Blunt, John Krasinski, Millicent Simmonds"
  },
  {
    id: "m19",
    title: "Gladiator",
    poster: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/Ar7xI9U3H86fUvYx33p42aY3Pau.jpg",
    genre: ["Action", "Adventure", "Drama"],
    rating: 8.5,
    year: 2000,
    runtime: 155,
    description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    mood: ["Action-packed", "Emotional", "Thought-provoking"],
    trailer: "P5ieIbInFpg",
    streaming: ["Paramount+", "Apple TV"],
    director: "Ridley Scott",
    cast: "Russell Crowe, Joaquin Phoenix, Connie Nielsen"
  },
  {
    id: "m20",
    title: "Your Name.",
    poster: "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6qFsPwaMisQW.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/dIWwZW7dJJ1qC6CWEsqv7ZNAvnL.jpg",
    genre: ["Animation", "Drama", "Fantasy"],
    rating: 8.4,
    year: 2016,
    runtime: 106,
    description: "Two strangers find themselves linked in a bizarre way. When a connection is formed, will distance be the only thing to keep them apart?",
    mood: ["Emotional", "Relaxing", "Thought-provoking"],
    trailer: "xU47nhruN-k",
    streaming: ["Crunchyroll", "Apple TV"],
    director: "Makoto Shinkai",
    cast: "Ryunosuke Kamiki, Mone Kamishibai, Ryo Narita"
  },
  {
    id: "m21",
    title: "Everything Everywhere All at Once",
    poster: "https://image.tmdb.org/t/p/w500/rKgvLsnO3Z4iF167kU77s04OaH4.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/wPU78OPN4BYEgWYdXyg0phMee61.jpg",
    genre: ["Action", "Comedy", "Sci-Fi"],
    rating: 8.7,
    year: 2022,
    runtime: 139,
    description: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
    mood: ["Thought-provoking", "Action-packed", "Emotional"],
    trailer: "wxN1T1uxQ2g",
    streaming: ["Paramount+", "Showtime"],
    director: "Daniel Kwan, Daniel Scheinert",
    cast: "Michelle Yeoh, Stephanie Hsu, Ke Huy Quan"
  },
  {
    id: "m22",
    title: "Titanic",
    poster: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/yDI6D5ZQh67YU4r2ms8qcSbAviZ.jpg",
    genre: ["Romance", "Drama", "Adventure"],
    rating: 7.9,
    year: 1997,
    runtime: 194,
    description: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
    mood: ["Emotional", "Relaxing", "Thought-provoking"],
    trailer: "CHekzSiETOE",
    streaming: ["Paramount+", "Apple TV"],
    director: "James Cameron",
    cast: "Leonardo DiCaprio, Kate Winslet, Billy Zane"
  },
  {
    id: "m23",
    title: "The Grand Budapest Hotel",
    poster: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWX9NZkt5BW.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/bbHQZpmr9c1Jm0zC4B1ZkP3pU0y.jpg",
    genre: ["Comedy", "Adventure", "Mystery"],
    rating: 8.1,
    year: 2014,
    runtime: 100,
    description: "A writer encounters the owner of an aging European hotel between the wars and learns of his early years serving as a lobby boy in the hotel's glorious years.",
    mood: ["Relaxing", "Thought-provoking", "Suspenseful"],
    trailer: "1Fg5iWmQjwk",
    streaming: ["Disney+", "Apple TV"],
    director: "Wes Anderson",
    cast: "Ralph Fiennes, F. Murray Abraham, Mathieu Amalric"
  },
  {
    id: "m24",
    title: "Knives Out",
    poster: "https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg",
    genre: ["Mystery", "Comedy", "Crime"],
    rating: 7.9,
    year: 2019,
    runtime: 130,
    description: "A detective investigates the death of a patriarch of an eccentric, combative family. When his death is deemed a suicide, the detective keeps investigating, slowly revealing a web of secrets.",
    mood: ["Suspenseful", "Thought-provoking", "Relaxing"],
    trailer: "qGqiHJTsRkQ",
    streaming: ["Netflix", "Prime Video"],
    director: "Rian Johnson",
    cast: "Daniel Craig, Chris Evans, Ana de Armas"
  },
  {
    id: "m25",
    title: "Pride & Prejudice",
    poster: "https://image.tmdb.org/t/p/w500/sGjIvtjeUQeBcZeJQ9Bp9Fd5T9f.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/5n2r5gEaV9uUv4k87E4C3KkF8iA.jpg",
    genre: ["Romance", "Drama"],
    rating: 7.8,
    year: 2005,
    runtime: 129,
    description: "Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy. But Mr. Darcy reluctantly finds himself falling in love with a woman beneath his class.",
    mood: ["Emotional", "Relaxing"],
    trailer: "1dCHLCK8HFE",
    streaming: ["Netflix", "Prime Video"],
    director: "Joe Wright",
    cast: "Keira Knightley, Matthew Macfadyen, Judi Dench"
  },
  {
    id: "m26",
    title: "The Shining",
    poster: "https://image.tmdb.org/t/p/w500/xazWoLealQwEgqZ89MLZklLZD3k.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/mmd1HnuvAzFc4iuVJcnBrh29Ahc.jpg",
    genre: ["Horror", "Mystery", "Thriller"],
    rating: 8.4,
    year: 1980,
    runtime: 146,
    description: "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrifying glimpses of the past and future.",
    mood: ["Scary", "Suspenseful", "Thought-provoking"],
    trailer: "S014oGZiSdI",
    streaming: ["HBO Max", "Apple TV"],
    director: "Stanley Kubrick",
    cast: "Jack Nicholson, Shelley Duvall, Danny Lloyd"
  },
  {
    id: "m27",
    title: "The Wolf of Wall Street",
    poster: "https://image.tmdb.org/t/p/w500/34m2tygAYBGqA9MXKhRDtzYd4MR.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7nO5DUMnCr2U744Lh45s5vM9Vvj.jpg",
    genre: ["Comedy", "Crime", "Drama"],
    rating: 8.2,
    year: 2013,
    runtime: 180,
    description: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
    mood: ["Action-packed", "Thought-provoking", "Suspenseful"],
    trailer: "iszwZqnIEYk",
    streaming: ["Netflix", "Paramount+"],
    director: "Martin Scorsese",
    cast: "Leonardo DiCaprio, Jonah Hill, Margot Robbie"
  }
];

const gamesData = [
  {
    id: "g1",
    title: "The Witcher 3: Wild Hunt",
    cover: "images/posters/g1.jpg",
    genre: ["RPG", "Action", "Fantasy"],
    platform: ["PC", "PlayStation", "Xbox", "Nintendo Switch"],
    rating: 9.7,
    year: 2015,
    description: "Geralt of Rivia, a monster hunter, embarks on a quest to find his adoptive daughter Ciri, who is being pursued by the Wild Hunt.",
    mood: ["Action-packed", "Emotional", "Thought-provoking"],
    trailer: "XHPrwv6Nggc",
    developer: "CD Projekt Red"
  },
  {
    id: "g2",
    title: "Elden Ring",
    cover: "images/posters/elden-ring.png",
    genre: ["RPG", "Action", "Dark Fantasy"],
    platform: ["PC", "PlayStation", "Xbox"],
    rating: 9.6,
    year: 2022,
    description: "In the Lands Between ruled by Queen Marika the Eternal, the Elden Ring has been shattered. The Tarnished must rise and become the Elden Lord.",
    mood: ["Action-packed", "Scary", "Thought-provoking"],
    trailer: "E3Huy2cdih0",
    developer: "FromSoftware"
  },
  {
    id: "g3",
    title: "Red Dead Redemption 2",
    cover: "images/posters/g3.jpg",
    genre: ["Action", "Adventure", "Open World"],
    platform: ["PC", "PlayStation", "Xbox"],
    rating: 9.8,
    year: 2018,
    description: "Amidst the decline of the Wild West, outlaw Arthur Morgan and the Van der Linde gang struggle to survive against government forces and rival gangs.",
    mood: ["Emotional", "Thought-provoking", "Action-packed"],
    trailer: "eaW0tYxiHgU",
    developer: "Rockstar Games"
  },
  {
    id: "g4",
    title: "The Legend of Zelda: Breath of the Wild",
    cover: "images/posters/g4.jpg",
    genre: ["Adventure", "Action", "Open World"],
    platform: ["Nintendo Switch"],
    rating: 9.5,
    year: 2017,
    description: "After a 100-year slumber, Link awakens in a ruined Hyrule. He must regain his memories and defeat Calamity Ganon to save Zelda.",
    mood: ["Relaxing", "Thought-provoking", "Action-packed"],
    trailer: "zw47_q9wbBE",
    developer: "Nintendo EPD"
  },
  {
    id: "g5",
    title: "Cyberpunk 2077",
    cover: "images/posters/g5.jpg",
    genre: ["RPG", "Sci-Fi", "Action"],
    platform: ["PC", "PlayStation", "Xbox"],
    rating: 8.6,
    year: 2020,
    description: "V is a mercenary outlaw fighting through the dystopian metropolis of Night City, seeking a one-of-a-kind implant that is the key to immortality.",
    mood: ["Action-packed", "Thought-provoking", "Suspenseful"],
    trailer: "8X2kIfS6fb8",
    developer: "CD Projekt Red"
  },
  {
    id: "g6",
    title: "God of War Ragnarök",
    cover: "images/posters/g6.jpg",
    genre: ["Action", "Adventure", "Mythology"],
    platform: ["PlayStation"],
    rating: 9.5,
    year: 2022,
    description: "Kratos and his teenage son Atreus travel through the Nine Realms of Norse mythology as Fimbulwinter prepares for Ragnarök.",
    mood: ["Action-packed", "Emotional", "Thought-provoking"],
    trailer: "hfJ4Km46A-0",
    developer: "Santa Monica Studio"
  },
  {
    id: "g7",
    title: "Hades",
    cover: "images/posters/g7.jpg",
    genre: ["Roguelike", "Action", "Indie"],
    platform: ["PC", "PlayStation", "Xbox", "Nintendo Switch"],
    rating: 9.3,
    year: 2020,
    description: "As the Prince of the Underworld, Zagreus attempts to battle his way out of the domain of his overbearing father, Hades.",
    mood: ["Action-packed", "Relaxing", "Emotional"],
    trailer: "Bz8l935B70k",
    developer: "Supergiant Games"
  },
  {
    id: "g8",
    title: "Minecraft",
    cover: "images/posters/g8.jpg",
    genre: ["Sandbox", "Survival"],
    platform: ["PC", "PlayStation", "Xbox", "Nintendo Switch"],
    rating: 9.0,
    year: 2011,
    description: "Explore infinite blocky worlds, craft items, build structures, and survive monsters in this ultimate creative and survival experience.",
    mood: ["Relaxing", "Thought-provoking"],
    trailer: "MmB9b5njVbA",
    developer: "Mojang Studios"
  },
  {
    id: "g9",
    title: "Portal 2",
    cover: "images/posters/g9.jpg",
    genre: ["Puzzle", "Sci-Fi", "Comedy"],
    platform: ["PC", "PlayStation", "Xbox", "Nintendo Switch"],
    rating: 9.8,
    year: 2011,
    description: "Trapped in the Aperture Science facility, Chell must navigate mind-bending portal puzzles and outsmart the rogue AI GLaDOS and the bumbling Wheatley.",
    mood: ["Thought-provoking", "Relaxing", "Suspenseful"],
    trailer: "tax4e4hBB43",
    developer: "Valve"
  },
  {
    id: "g10",
    title: "Resident Evil 4 (Remake)",
    cover: "images/posters/g10.jpg",
    genre: ["Horror", "Action", "Thriller"],
    platform: ["PC", "PlayStation", "Xbox"],
    rating: 9.4,
    year: 2023,
    description: "Six years after the Raccoon City disaster, agent Leon S. Kennedy is sent to rescue the US President's kidnapped daughter from a secluded European village.",
    mood: ["Scary", "Suspenseful", "Action-packed"],
    trailer: "j5XvDVZ92rU",
    developer: "Capcom"
  },
  {
    id: "g11",
    title: "Hollow Knight",
    cover: "images/posters/g11.jpg",
    genre: ["Metroidvania", "Indie", "Adventure"],
    platform: ["PC", "PlayStation", "Xbox", "Nintendo Switch"],
    rating: 9.4,
    year: 2017,
    description: "Descend into the ruined kingdom of Hallownest, a vast subterranean world filled with bugs, ancient secrets, and challenging boss battles.",
    mood: ["Relaxing", "Emotional", "Thought-provoking"],
    trailer: "UAO2urG23S4",
    developer: "Team Cherry"
  },
  {
    id: "g12",
    title: "GTA V",
    cover: "images/posters/g12.png",
    genre: ["Action", "Open World", "Crime"],
    platform: ["PC", "PlayStation", "Xbox"],
    rating: 9.5,
    year: 2013,
    description: "Three very different criminals team up to execute a series of daring and dangerous heists across the sprawling metropolis of Los Santos.",
    mood: ["Action-packed", "Suspenseful"],
    trailer: "QkkoHAzjnUs",
    developer: "Rockstar North"
  },
  {
    id: "g13",
    title: "Marvel's Spider-Man 2",
    cover: "images/posters/g13.jpg",
    genre: ["Action", "Adventure", "Superhero"],
    platform: ["PlayStation"],
    rating: 9.2,
    year: 2023,
    description: "Spider-Men Peter Parker and Miles Morales face ultimate tests of strength as they fight to save New York City from Venom and Kraven the Hunter.",
    mood: ["Action-packed", "Emotional", "Suspenseful"],
    trailer: "bgqGdIoa52s",
    developer: "Insomniac Games"
  },
  {
    id: "g14",
    title: "Baldur's Gate 3",
    cover: "images/posters/g14.jpg",
    genre: ["RPG", "Fantasy"],
    platform: ["PC", "PlayStation", "Xbox"],
    rating: 9.8,
    year: 2023,
    description: "Gather your party and return to the Forgotten Realms in a tale of fellowship, betrayal, sacrifice, and the lure of absolute power.",
    mood: ["Thought-provoking", "Emotional", "Action-packed"],
    trailer: "Ug35RLya5tQ",
    developer: "Larian Studios"
  },
  {
    id: "g15",
    title: "Stardew Valley",
    cover: "images/posters/g15.png",
    genre: ["Simulation", "Indie", "RPG"],
    platform: ["PC", "PlayStation", "Xbox", "Nintendo Switch"],
    rating: 9.2,
    year: 2016,
    description: "You've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to build a new life.",
    mood: ["Relaxing", "Emotional"],
    trailer: "ot7uXNQsk0g",
    developer: "ConcernedApe"
  },
  {
    id: "g16",
    title: "Alan Wake 2",
    cover: "images/posters/g16.jpg",
    genre: ["Horror", "Mystery", "Thriller"],
    platform: ["PC", "PlayStation", "Xbox"],
    rating: 9.1,
    year: 2023,
    description: "An FBI agent investigating ritualistic murders in Bright Falls and a trapped writer attempting to write himself out of a dark dimension find their realities intertwined.",
    mood: ["Scary", "Suspenseful", "Thought-provoking"],
    trailer: "dlQ3X49KAoo",
    developer: "Remedy Entertainment"
  },
  {
    id: "g17",
    title: "Super Mario Odyssey",
    cover: "images/posters/g17.jpg",
    genre: ["Platformer", "Adventure", "Family"],
    platform: ["Nintendo Switch"],
    rating: 9.4,
    year: 2017,
    description: "Join Mario on a massive, globe-trotting 3D adventure using his new ally Cappy to rescue Princess Peach from Bowser's wedding plans.",
    mood: ["Relaxing", "Action-packed"],
    trailer: "wGQHQc_3yYo",
    developer: "Nintendo EPD"
  },
  {
    id: "g18",
    title: "The Last of Us Part I",
    cover: "images/posters/g18.jpg",
    genre: ["Action", "Adventure", "Post-Apocalyptic"],
    platform: ["PC", "PlayStation"],
    rating: 9.6,
    year: 2022,
    description: "In a ravaged civilization where infected and hardened survivors run rampant, Joel, a weary protagonist, is hired to smuggle 14-year-old Ellie out of a military quarantine zone.",
    mood: ["Emotional", "Action-packed", "Suspenseful"],
    trailer: "WxjeV10H1F0",
    developer: "Naughty Dog"
  },
  {
    id: "g19",
    title: "Persona 5 Royal",
    cover: "images/posters/g19.jpg",
    genre: ["RPG", "Anime", "Turn-Based"],
    platform: ["PC", "PlayStation", "Xbox", "Nintendo Switch"],
    rating: 9.5,
    year: 2019,
    description: "Transferring to a Tokyo high school, Joker discovers supernatural powers and forms the Phantom Thieves of Hearts to reform corrupt adults.",
    mood: ["Thought-provoking", "Relaxing", "Emotional"],
    trailer: "SKpSpvD7b1A",
    developer: "ATLUS"
  },
  {
    id: "g20",
    title: "Outer Wilds",
    cover: "images/posters/g20.jpg",
    genre: ["Adventure", "Sci-Fi", "Mystery"],
    platform: ["PC", "PlayStation", "Xbox", "Nintendo Switch"],
    rating: 9.4,
    year: 2019,
    description: "You are the newest recruit of Outer Wilds Ventures, a fledgling space program searching for answers in a strange, constantly evolving solar system trapped in an infinite time loop.",
    mood: ["Thought-provoking", "Relaxing", "Emotional"],
    trailer: "d6LGNVCL1fs",
    developer: "Mobius Digital"
  },
  {
    id: "g21",
    title: "Disco Elysium",
    cover: "images/posters/g21.jpg",
    genre: ["RPG", "Detective", "Indie"],
    platform: ["PC", "PlayStation", "Xbox", "Nintendo Switch"],
    rating: 9.6,
    year: 2019,
    description: "You're a detective with a unique skill system at your disposal and a whole city block to carve your path across. Interrogate unforgettable characters or take bribes.",
    mood: ["Thought-provoking", "Emotional", "Relaxing"],
    trailer: "M89a1iH9tM4",
    developer: "ZA/UM"
  }
];

const actorsData = [
  { id: "a1", name: "Leonardo DiCaprio", role: "Actor", knownFor: "Inception, Titanic, Shutter Island", image: "https://image.tmdb.org/t/p/w185/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg" },
  { id: "a2", name: "Christian Bale", role: "Actor", knownFor: "The Dark Knight, American Psycho", image: "https://image.tmdb.org/t/p/w185/b7fTC9WFkgqGOv77mLQeg9KaHJn.jpg" },
  { id: "a3", name: "Matthew McConaughey", role: "Actor", knownFor: "Interstellar, True Detective", image: "https://image.tmdb.org/t/p/w185/eDVLbO2xY1pB6uE2U9b2g0n7J4w.jpg" },
  { id: "a4", name: "Michelle Yeoh", role: "Actress", knownFor: "Everything Everywhere All at Once", image: "https://image.tmdb.org/t/p/w185/eQ7jC0kFuh1v2u0h4q6k2S0j3D3.jpg" },
  { id: "a5", name: "Song Kang-ho", role: "Actor", knownFor: "Parasite, Snowpiercer", image: "https://image.tmdb.org/t/p/w185/hVvO208M7hEwB0hN9E1aYmXgJ7j.jpg" },
  { id: "a6", name: "Cillian Murphy", role: "Actor", knownFor: "Oppenheimer, Peaky Blinders", image: "https://image.tmdb.org/t/p/w185/3Dq5m1wTfZ9aYm4K7uQ1u5D7X0c.jpg" },
  { id: "a7", name: "Miles Teller", role: "Actor", knownFor: "Whiplash, Top Gun: Maverick", image: "https://image.tmdb.org/t/p/w185/cg3LWv67q7Wc1w3B3p0h9o9u4u3.jpg" },
  { id: "a8", name: "Anne Hathaway", role: "Actress", knownFor: "Interstellar, The Dark Knight Rises", image: "https://image.tmdb.org/t/p/w185/tLspl9vRJw4v1E2n5g7X0b9U7y3.jpg" }
];

const directorsData = [
  { id: "d1", name: "Christopher Nolan", role: "Director", knownFor: "Inception, The Dark Knight, Interstellar", image: "https://image.tmdb.org/t/p/w185/xuAIHGbhww909e7018cQh6yM0nI.jpg" },
  { id: "d2", name: "Hayao Miyazaki", role: "Director", knownFor: "Spirited Away, Princess Mononoke", image: "https://image.tmdb.org/t/p/w185/vA9z5oP0kF4tqL2m9B8q4x1U2j7.jpg" },
  { id: "d3", name: "Bong Joon Ho", role: "Director", knownFor: "Parasite, Memories of Murder", image: "https://image.tmdb.org/t/p/w185/5yL6m7uT0kX9y1p2w3q4r5t6y7u.jpg" },
  { id: "d4", name: "Damien Chazelle", role: "Director", knownFor: "Whiplash, La La Land", image: "https://image.tmdb.org/t/p/w185/eY9o3p3u7X2u5b8m0w4q7x1u2j7.jpg" },
  { id: "d5", name: "Ridley Scott", role: "Director", knownFor: "Gladiator, Blade Runner", image: "https://image.tmdb.org/t/p/w185/wSm77b4Zp439W2wGfM9y8vU0K4G.jpg" },
  { id: "d6", name: "Makoto Shinkai", role: "Director", knownFor: "Your Name., Weathering With You", image: "https://image.tmdb.org/t/p/w185/m1vO208M7hEwB0hN9E1aYmXgJ7j.jpg" }
];

const providersData = [
  { id: "p1", name: "Netflix", type: "STREAM", icon: "fa-solid fa-play", color: "#e50914" },
  { id: "p2", name: "Prime Video", type: "STREAM", icon: "fa-solid fa-film", color: "#00a8e1" },
  { id: "p3", name: "Disney+", type: "STREAM", icon: "fa-solid fa-sparkles", color: "#113ccf" },
  { id: "p4", name: "JioHotstar", type: "STREAM", icon: "fa-solid fa-star", color: "#ffaa00" },
  { id: "p5", name: "Apple TV", type: "RENT", icon: "fa-brands fa-apple", color: "#ffffff" },
  { id: "p6", name: "HBO Max", type: "STREAM", icon: "fa-solid fa-tv", color: "#9933ff" },
  { id: "p7", name: "Hulu", type: "STREAM", icon: "fa-solid fa-clapperboard", color: "#1ce783" }
];

// Enrich default items with missing metadata fields if not set
moviesData.forEach((m, idx) => {
  if (!m.language) m.language = idx % 2 === 0 ? "English" : (idx % 3 === 0 ? "Japanese" : "Korean");
  if (!m.country) m.country = idx % 3 === 0 ? "USA" : (idx % 4 === 0 ? "Japan" : "South Korea");
  if (!m.matchPercentage) m.matchPercentage = 85 + (idx % 15);
});

gamesData.forEach((g, idx) => {
  if (!g.tags) g.tags = ["Open World", "Story Rich", "Singleplayer", "Atmospheric"];
  if (!g.price) g.price = idx % 3 === 0 ? "Free" : `₹${999 + (idx * 200 % 2500)}`;
  if (!g.publisher) g.publisher = g.developer || "Global Publishing";
  if (!g.features) g.features = ["Controller Support", "Achievements", "Cloud Saves"];
  if (!g.sysReq) {
    g.sysReq = {
      minimum: "OS: Windows 10 (64-bit) | CPU: Intel Core i5-8400 / AMD Ryzen 5 2600 | RAM: 8 GB | GPU: NVIDIA GTX 1060 / AMD RX 580 | Storage: 60 GB",
      recommended: "OS: Windows 11 (64-bit) | CPU: Intel Core i7-10700K / AMD Ryzen 7 3700X | RAM: 16 GB | GPU: NVIDIA RTX 3070 / AMD RX 6700 XT | Storage: 60 GB SSD"
    };
  }
  if (!g.matchPercentage) g.matchPercentage = 88 + (idx % 12);
});

// Export datasets to global scope or export module
if (typeof module !== "undefined" && module.exports) {
  module.exports = { moviesData, gamesData, actorsData, directorsData, providersData };
} else {
  window.moviesData = moviesData;
  window.gamesData = gamesData;
  window.actorsData = actorsData;
  window.directorsData = directorsData;
  window.providersData = providersData;
}

